config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  resources :tasks

  devise_for :users, skip: [:registrations]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :creator, class_name: 'User', foreign_key: 'created_by'

  enum status: { todo: 0, doing: 1, done: 2 }

  validates :title, presence: true, length: { maximum: 200 }
  validates :content, presence: true, length: { maximum: 1000 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks
  # TODO: relationあとで
  # has_many :tasks, class_name: 'Task', :foreign_key => 'user_id'
  # has_many :tasks, class_name: 'Task', :foreign_key => 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    added_attrs = [ :email, :username, :password, :password_confirmation ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs

    #devise_parameter_sanitizer.permit :invite, keys: [:email]
    devise_parameter_sanitizer.permit :accept_invitation, keys: [:username, :password, :password_confirmation]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all.order(status: :asc, id: :desc)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.creator = current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:title, :content, :user_id, :status, :created_by)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Tasks
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    script src="https://cdn.jsdelivr.net/npm/vue-js-modal@1.3.31/dist/index.min.js"
    link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet" /
    link href="https://cdn.jsdelivr.net/npm/@mdi/font@4.x/css/materialdesignicons.min.css" rel="stylesheet" /
    link href="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.min.css" rel="stylesheet" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, minimal-ui" name="viewport" /

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body style="padding: 10px;"
    -#TODO: styleのベタがきをやめる
    header style="margin-botton: 10px;"
      nav
        - if user_signed_in?
          strong= "ログインユーザー名: #{current_user.username}"
          / #TODO: プロフィール変更機能はあってもいい
          /.edit-profile= link_to 'プロフィール変更', edit_user_registration_path
          span.logout style="margin-left: 80px;"
            = link_to 'ログアウトする', destroy_user_session_path, method: :delete
        - else
          .login= link_to 'ログインする', new_user_session_path
    p.notice
      = notice
    p.alert
      = alert
    script src="https://cdn.jsdelivr.net/npm/vue@2.x/dist/vue.js"
    script src="https://cdn.jsdelivr.net/npm/vuetify@2.x/dist/vuetify.js"
    = yield

app/views/pages/index.html.slim
h1 Pages#index
p Find me in app/views/pages/index.html.slim

app/views/pages/show.html.slim
h1 Pages#show
p Find me in app/views/pages/show.html.slim

app/views/tasks/_form.html.slim
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :status
    = f.number_field :status
  .actions = f.submit

app/views/tasks/_index.html.slim
h1 Listing tasks

.container.js-tasksIndex
  table
    thead
      tr
        th タイトル
        th 内容
        th 担当者
        th 登録者
        th 状態
        th

    tbody v-for="task in tasks"

      tr
        td = "{{task.title}}"
        td = "{{task.content}}"
        td = "{{task.user}}"
        td = "{{task.creator}}"
        td = "{{task.status}}"
        td
          button v-on:click="showModal(task.id)" 詳細
          button v-on:click="showFormModal(task)" 編集
          button v-on:click="deleteTask(task)" 削除

  button.btn.btn-primary.my-2 v-on:click="showFormModal(null)" タスク登録

  modal :height="400" name="task-modal"
    .card
      .card-body
        .card-title
          h2(v-if="createFlg")　タスク登録
          h2(v-else) タスク編集
        form.card-text autocomplete="off"
          .form-group
            label for="title"  TITLE
            input#title.form-control placeholder="タイトルを入力してください" type="text" v-model="form.title"
          .form-group
            label for="content"  CONTENT
            input#content.form-control placeholder="詳細を入力してください" type="text" v-model="form.content"
          .form-group
            label for="user-id"  user_id
            input#user-id.form-control placeholder="user_id" type="text" v-model="form.user_id"
          .form-group
            label for="created-by"  created_by
            input#created-by.form-control placeholder="created_by" type="text" v-model="form.created_by"
          .form-group
            label for="status"  STATUS
            input#status.form-control placeholder="status" type="text" v-model="form.status"
          button.btn.btn-primary(v-on:click="createTask" v-if="createFlg") 登録
          button.btn.btn-primary(v-on:click="updateTask" v-else) 更新

  modal :height="400" name="task-show-modal"
    .card
      .card-body
        .card-title
          h2 タスク詳細
        form.card-text
          span.card-title
            = "{{ taskInfo.title }}"
          .detail
            = "{{ taskInfo.content }}"
          .user
            = "{{ taskInfo.user}}"
          .creator
            = "{{ taskInfo.creator}}"
          .status
            = "{{ taskInfo.status}}"

= javascript_pack_tag 'tasks'

app/views/tasks/edit.html.slim
h1 Editing task

== render 'form'

=> link_to 'Show', @task
'|
=< link_to 'Back', tasks_path

app/views/tasks/index.html.erb
<h1>タスク管理</h1>
<div class="container js-tasksIndex">
  <v-app id="inspire">
    <v-col cols="3" >
      <v-btn class="" elevation="1" v-on:click="showFormModal(null)">
        <v-icon dark>mdi-note-plus-outline</v-icon>タスク登録
      </v-btn>
    </v-col>

    <v-simple-table>
      <template v-slot:default>
        <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-left">タイトル</th>
          <th class="text-left">内容</th>
          <th class="text-center">担当者</th>
          <th class="text-center">状態</th>
          <th class="text-center"></th>
        </tr>
        </thead>
        <tbody>
        <tr v-for="task in tasks" :key="task.id">
          <td class="text-center">{{ task.id }}</td>
          <td class="text-left">{{ task.title }}</td>
          <td class="text-left">{{ task.content }}</td>
          <td class="text-center">{{ task.user }}</td>
          <td class="text-center">{{ task.status }}</td>
          <td  class="text-center">
            <v-btn class="ma-2" elevation="1" v-on:click="showModal(task.id)">
              <v-icon dark>mdi-details</v-icon>詳細
            </v-btn>
            <v-btn class="ma-2" elevation="1" v-on:click="showFormModal(task)">
              <v-icon dark>mdi-circle-edit-outline</v-icon>編集
            </v-btn>
            <v-btn class="ma-2" elevation="1" v-on:click="deleteTask(task)">
              <v-icon dark>mdi-trash-can</v-icon>削除
            </v-btn>
          </td>
        </tr>
        </tbody>
      </template>
    </v-simple-table>

  <modal :height="400" name="task-modal">
    <v-form ref="form" v-model="valid">
      <v-container>
        <v-row>
          <v-col cols="12" >
            <v-text-field v-model="form.title" :rules="titleRules" label="タイトル" required></v-text-field>
          </v-col>
        </v-row>
        <v-row>
          <v-col cols="12">
            <v-text-field v-model="form.content" :rules="contentRules" label="内容" required></v-text-field>
          </v-col>
        </v-row>
        <v-row>
          <v-col cols="6">
            <v-text-field v-model="form.user_id" :rules="creatorRules" label="担当者" required></v-text-field>
          </v-col>
          <v-col cols="6">
            <v-select v-model="form.status" :items="statuses" :rules="[v => !!v || '状態は必須です']" label="状態" required>
            </v-select>
          </v-col>
        </v-row>
        <v-row>
          <v-col cols="3" v-if="createFlg">
            <v-btn class="ma-2" elevation="1"  v-on:click="createTask">登録</v-btn>
          </v-col>
          <v-col cols="3" v-else>
            <v-btn class="ma-2" elevation="1"  v-on:click="updateTask">更新</v-btn>
          </v-col>
        </v-row>
      </v-container>
    </v-form>
  </modal>

  <modal :height="400" name="task-show-modal">
    <div class="ma-6">
      <div class="text-subtitle-1">状態: {{taskInfo.status}}　　担当者: {{taskInfo.user}} </div>
      <p class="display-1 text--primary">
        {{taskInfo.title}}
      </p>
      <p class="text-body-1">{{taskInfo.content}}</p>
      <p class="text-caption">登録者: {{taskInfo.creator}} </p>
    </div>
  </modal>
</v-app>
</div>

<%= javascript_pack_tag 'tasks' %>

app/views/tasks/index.html.slim
h1 Listing tasks

.container.js-tasksIndex
  table
    thead
      tr
        th タイトル
        th 内容
        th 担当者
        th 登録者
        th 状態
        th

    tbody v-for="task in tasks"

      tr
        td = "{{task.title}}"
        td = "{{task.content}}"
        td = "{{task.user}}"
        td = "{{task.creator}}"
        td = "{{task.status}}"
        td
          button v-on:click="showModal(task.id)" 詳細
          button v-on:click="showFormModal(task)" 編集
          button v-on:click="deleteTask(task)" 削除

  button.btn.btn-primary.my-2 v-on:click="showFormModal(null)" タスク登録

  modal :height="400" name="task-modal"
    .card
      .card-body
        .card-title
          h2(v-if="createFlg")　タスク登録
          h2(v-else) タスク編集
        form.card-text autocomplete="off"
          .form-group
            label for="title"  TITLE
            input#title.form-control placeholder="タイトルを入力してください" type="text" v-model="form.title"
          .form-group
            label for="content"  CONTENT
            input#content.form-control placeholder="詳細を入力してください" type="text" v-model="form.content"
          .form-group
            label for="user-id"  user_id
            input#user-id.form-control placeholder="user_id" type="text" v-model="form.user_id"
          .form-group
            label for="created-by"  created_by
            input#created-by.form-control placeholder="created_by" type="text" v-model="form.created_by"
          .form-group
            label for="status"  STATUS
            input#status.form-control placeholder="status" type="text" v-model="form.status"
          button.btn.btn-primary(v-on:click="createTask" v-if="createFlg") 登録
          button.btn.btn-primary(v-on:click="updateTask" v-else) 更新

  modal :height="400" name="task-show-modal"
    .card
      .card-body
        .card-title
          h2 タスク詳細
        form.card-text
          span.card-title
            = "{{ taskInfo.title }}"
          .detail
            = "{{ taskInfo.content }}"
          .user
            = "{{ taskInfo.user}}"
          .creator
            = "{{ taskInfo.creator}}"
          .status
            = "{{ taskInfo.status}}"

= javascript_pack_tag 'tasks'

app/views/tasks/new.html.slim
h1 New task

== render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.slim
p#notice = notice

p
  strong Title:
  = @task.title
p
  strong Content:
  = @task.content
p
  strong User:
  = @task.user
p
  strong Status:
  = @task.status

=> link_to 'Edit', edit_task_path(@task)
'|
=< link_to 'Back', tasks_path